import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import HeroText from "../Components/HeroText/HeroText";
import styles from "../styles/Home.module.css";
import tableStyles from "../styles/Table.module.css";
import LeetQuestion from "../types/LeetQuestion";
import TableHead from "../Components/TableHead/TableHead";
import SortOption from "../types/SortOption";
import {
  compareDifficulties,
  compareDislikes,
  compareLikes,
  compareNumber,
  comparePercentLiked,
  compareTitles,
} from "../Utils/SortFuncs";
import QuestionTableRow from "../Components/Row/TableRow";
import {
  speakJson,
  blindJson,
  amazonJSON,
  googleJSON,
  allJson,
  singleQuestion,
  singleQuestionOpt,
  datasetOpts,
  difficultyOpts,
} from "../consts/Consts";
import LeetQuestionOpt from "../types/LeetQuestionOptions";
import findFunc from "../Utils/FindFuncs";
import joinClasses from "../Utils/joinClasses";
import { getVids } from "../Utils/FetchFuncs";
import compareTime from "../Utils/TimeFunc";

function clockRender(assessmentStarted: boolean, assessmentTimer: number): any {
  /* assessmentStarted
    ? `${Math.floor(assessmentTimer / 60)}h:${
        assessmentTimer % 60 > 9
          ? (assessmentTimer % 60) + "m"
          : "0" + (assessmentTimer % 60) + "m"
      }`
    : ""; */

  if (assessmentStarted) {
    return (
      <p>
        <span>{Math.floor(assessmentTimer / 60)}</span>h {"  "}
        <span>
          {assessmentTimer % 60 > 9
            ? assessmentTimer % 60
            : "0" + (assessmentTimer % 60)}
        </span>
        m
      </p>
    );
  }
  return <p></p>;
}
const Home: NextPage = () => {
  const [fullProblemList, setfullProblemList] = useState(speakJson);
  const [problemList, setproblemList] = useState(fullProblemList);
  const [assesmentProblemList, setassesmentProblemList] = useState<
    LeetQuestionOpt[]
  >([singleQuestionOpt, singleQuestionOpt]);
  const [randNum, setrandNum] = useState("10");
  const [assessmentTimer, setassessmentTimer] = useState(105);
  const [assessmentStarted, setassessmentStarted] = useState(false);
  const [assessmentFinished, setassessmentFinished] = useState(false);
  const [intervalId, setIntervalId] = useState<NodeJS.Timer>();
  const [sortOption, setsortOption] = useState({
    isAscending: false,
    category: "Number",
  });
  //const [showForm, setshowForm] = useState<boolean | null>(null);
  const [vidList, setVidList] = useState([]);
  function getRandom(arr: any[], n: number) {
    let result = new Array(n),
      len = arr.length,
      taken = new Array(len);
    if (n > len)
      throw new RangeError("getRandom: more elements taken than available");
    while (n--) {
      const x = Math.floor(Math.random() * len);
      result[n] = arr[x in taken ? taken[x] : x];
      taken[x] = --len in taken ? taken[len] : len;
    }
    return result;
  }
  function getRandList(
    possibleSelection: any,
    jsonList: LeetQuestion[],
    setList: (val: any[]) => void
  ) {
    if (
      typeof possibleSelection != "string" ||
      isNaN(parseInt(possibleSelection))
    ) {
      return;
    }
    let selectionNum = parseInt(possibleSelection);
    if (selectionNum > jsonList.length) {
      //selectionNum = jsonList.length;
      setList(jsonList);
      return;
    }
    setproblemList(getRandom(jsonList, selectionNum));
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroText
          bodyText="Choose a curated set of Leetcode questions to practice, or get a random selection!"
          headingText="Improve Your Skills!"
        />
        <div id={tableStyles.tableButtonDiv}>
          <div>
            <label htmlFor="problem_num">How many random questions?</label>

            <input
              name="problem_num"
              id="problem_num"
              onChange={(e) => {
                setrandNum(e.target.value);
              }}
            ></input>
            <button
              onClick={() => {
                getRandList(randNum, fullProblemList, setproblemList);
                setsortOption({ isAscending: false, category: "Number" });
              }}
            >
              Get Problems
            </button>
          </div>

          <div id={tableStyles.selectDiv}>
            <label htmlFor="questionlist">Choose a question set</label>
            <select
              name="questionlist"
              id="questionSelect"
              onChange={() => {
                setsortOption({ isAscending: false, category: "Number" });
              }}
            >
              <option
                onClick={() => {
                  setfullProblemList(speakJson);
                  setproblemList(speakJson);
                }}
              >
                Speak Questions
              </option>
              <option
                onClick={() => {
                  setfullProblemList(blindJson);
                  setproblemList(blindJson);
                }}
              >
                Blind 75
              </option>
              <option
                onClick={() => {
                  setfullProblemList(amazonJSON);
                  setproblemList(amazonJSON);
                }}
              >
                Amazon Questions
              </option>
              <option
                onClick={() => {
                  setfullProblemList(googleJSON);
                  setproblemList(googleJSON);
                }}
              >
                Google Questions
              </option>
              <option
                onClick={() => {
                  setfullProblemList(allJson);
                  setproblemList(allJson);
                }}
              >
                All Questions
              </option>
            </select>
          </div>
        </div>
        <div>
          <h4>Create practice test!</h4>

          <details id={"assessmentFormHolder"}>
            <summary>Create test form</summary>
            <div className={tableStyles.subForm}>
              <div className={tableStyles.selectColDiv}>
                <label htmlFor={`AssesmentDatasetSelectionAll`}>
                  Dataset For All
                </label>
                <select
                  name={`AssesmentDatasetSelectionAll`}
                  id={`AssesmentDatasetSelectionAll`}
                  defaultValue={""}
                >
                  {datasetOpts.map((datasetNameVal, n) => (
                    <option
                      key={`companyOpt${n}ForSelectAll`}
                      onClick={() => {
                        setassesmentProblemList([
                          ...assesmentProblemList.map((val, ind) => {
                            const nVal: LeetQuestionOpt = { ...val };
                            nVal.dataset = datasetNameVal;
                            return nVal;
                          }),
                        ]);
                      }}
                    >
                      {datasetNameVal}
                    </option>
                  ))}
                </select>
              </div>
              <ul>
                {assesmentProblemList.map((val, i) => (
                  <li
                    className={tableStyles.problemListQuestion}
                    key={`AssesmentQuestionNum${i}`}
                  >
                    <h6> {`Question ${i + 1}`}</h6>
                    <div className={tableStyles.selectColDiv}>
                      <label htmlFor={`AssesmentDatasetSelection${i}`}>
                        Dataset
                      </label>
                      <select
                        name={`AssesmentDatasetSelection${i}`}
                        id={`AssesmentDatasetSelection${i}`}
                        value={assesmentProblemList[i].dataset}
                        onChange={() => {}}
                      >
                        {datasetOpts.map((datasetNameVal, n) => (
                          <option
                            key={`companyOpt${n}ForSelect${i}`}
                            onClick={() => {
                              setassesmentProblemList([
                                ...assesmentProblemList.map((val, ind) => {
                                  if (ind === i) {
                                    const nVal: LeetQuestionOpt = { ...val };
                                    nVal.dataset = datasetNameVal;
                                    return nVal;
                                  }
                                  return val;
                                }),
                              ]);
                            }}
                          >
                            {datasetNameVal}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div className={tableStyles.selectColDiv}>
                      <label htmlFor={`AssesmentDifficultySelection${i}`}>
                        Difficulty
                      </label>
                      <select
                        name={`AssesmentDifficultySelection${i}`}
                        id={`AssesmentDifficultySelection${i}`}
                        value={assesmentProblemList[i].difficulty}
                        onChange={() => {}}
                      >
                        {difficultyOpts.map((difficultyNameVal, n) => (
                          <option
                            key={`difficultyOpt${n}ForSelect${i}`}
                            onClick={() => {
                              setassesmentProblemList([
                                ...assesmentProblemList.map((val, ind) => {
                                  if (ind === i) {
                                    const nVal: LeetQuestionOpt = { ...val };
                                    nVal.difficulty = difficultyNameVal;
                                    return nVal;
                                  }
                                  return val;
                                }),
                              ]);
                            }}
                          >
                            {difficultyNameVal}
                          </option>
                        ))}
                      </select>
                    </div>
                    <button
                      onClick={() => {
                        console.log(assesmentProblemList);
                        const firstHalf = assesmentProblemList.slice(0, i);
                        const secondHalf = assesmentProblemList.slice(i + 1);
                        setassesmentProblemList([...firstHalf, ...secondHalf]);
                      }}
                    >
                      X
                    </button>
                  </li>
                ))}
              </ul>
              <label htmlFor="assessmentDuration">How many minutes?</label>
              <input
                name="assessmentDuration"
                type={"number"}
                min={5}
                max={150}
                defaultValue={105}
                onChange={(e) => {
                  const timeInt = parseInt(e.target.value);
                  if (timeInt === NaN) {
                    return;
                  }
                  setassessmentTimer(parseInt(e.target.value));
                }}
              ></input>
              <div>
                <button
                  onClick={() => {
                    setassesmentProblemList([
                      ...assesmentProblemList,
                      singleQuestionOpt,
                    ]);
                  }}
                >
                  Add Question
                </button>
                {/* <button
                onClick={() => {
                  setassesmentProblemList([
                    ...assesmentProblemList.map((val) => {
                      return singleQuestionOpt;
                    }),
                  ]);
                }}
              >
                Reset All
              </button> */}
                <button
                  onClick={() => {
                    if (assessmentStarted) {
                      setassessmentStarted(false);
                      setassessmentFinished(true);
                      clearInterval(intervalId);
                      return;
                    }
                    const problemList = findFunc(assesmentProblemList);
                    console.log(problemList);
                    setproblemList([...problemList]);
                    setassessmentStarted(true);
                    const timePrev = new Date();
                    //Callback problem, it's
                    //getting and memorizing variable vals
                    //Not really a huge deal except for
                    //Stopping when timer hits 0
                    //And stopping the assessment
                    const intId = setInterval(() => {
                      console.log(
                        new Date().getTime() - timePrev.getTime(),
                        assessmentTimer * 60 * 1000
                      );
                      if (
                        new Date().getTime() - timePrev.getTime() >=
                        assessmentTimer * 60 * 1000
                      ) {
                        console.log("Done!");
                        clearInterval(intervalId);
                        setassessmentTimer((prev) => prev - 1);
                        getVids(problemList.map((val) => val.title));
                        return;
                      }

                      //console.log("Tick", assessmentTimer);
                      //compareTime(timeNow, assessmentTimer);
                      setassessmentTimer((prev) => prev - 1);
                    }, 1000 * 60);
                    setIntervalId(intId);
                  }}
                >
                  {assessmentStarted ? "Stop Assessment" : "Create Assessment"}
                </button>
                <div id={tableStyles.preTableSpaceDiv}>
                  {clockRender(assessmentStarted, assessmentTimer)}
                </div>
              </div>
            </div>
          </details>
        </div>
        <table id={tableStyles.table}>
          <thead>
            <tr>
              <TableHead
                sortFunc={compareNumber}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Number"
              />
              <TableHead
                sortFunc={compareDifficulties}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Difficulty"
              />
              <TableHead
                sortFunc={compareTitles}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Name"
              />
              <TableHead
                sortFunc={compareLikes}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Likes"
              />
              <TableHead
                sortFunc={compareDislikes}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Dislikes"
              />
              <TableHead
                sortFunc={comparePercentLiked}
                currentList={problemList}
                setCurrentList={setproblemList}
                setSortOption={setsortOption}
                sortOption={sortOption as SortOption}
                headText="Percent Liked"
              />
            </tr>
          </thead>
          <tbody id={tableStyles.tbody}>
            {problemList.map((val, i) => {
              if (val.title === "None") {
                return null;
              }
              return (
                <QuestionTableRow
                  key={`QuestionNum${i}`}
                  question={val}
                  number={i + 1}
                />
              );
            })}
          </tbody>
        </table>
        <div id="youtubeVids"></div>
        <p>
          Note: premium questions have been removed, which is why the blind 75
          only has 70 questions.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://personal2-1.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Daniel Felsenthal
        </a>
      </footer>
    </div>
  );
};

export default Home;
